<link rel="stylesheet" href="{{asset('/')}}front-assets/css/bootstrap.min.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/owl.carousel.min.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/slicknav.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/flaticon.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/progressbar_barfiller.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/gijgo.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/animate.min.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/animated-headline.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/magnific-popup.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/fontawesome-all.min.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/themify-icons.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/slick.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/nice-select.css">
<link rel="stylesheet" href="{{asset('/')}}front-assets/css/style.css">